// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAe9OhgIMgP3SU1A7MVjJ-F60ROUFmtk',
    appId: '1:1045040024438:web:c8e65e811102c480bc4857',
    messagingSenderId: '1045040024438',
    projectId: 'honbab-battle',
    authDomain: 'honbab-battle.firebaseapp.com',
    storageBucket: 'honbab-battle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGTPOnG8MAAyXjxHY0qPNheayHn66lRU',
    appId: '1:1045040024438:android:fdb2eb8003ae0e1ebc4857',
    messagingSenderId: '1045040024438',
    projectId: 'honbab-battle',
    storageBucket: 'honbab-battle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRcWXtno9P2BGlRWuEpWWHuioQXENsxw',
    appId: '1:1045040024438:ios:e1945070d7800931bc4857',
    messagingSenderId: '1045040024438',
    projectId: 'honbab-battle',
    storageBucket: 'honbab-battle.firebasestorage.app',
    iosBundleId: 'com.example.honbabBattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRcWXtno9P2BGlRWuEpWWHuioQXENsxw',
    appId: '1:1045040024438:ios:e1945070d7800931bc4857',
    messagingSenderId: '1045040024438',
    projectId: 'honbab-battle',
    storageBucket: 'honbab-battle.firebasestorage.app',
    iosBundleId: 'com.example.honbabBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMAe9OhgIMgP3SU1A7MVjJ-F60ROUFmtk',
    appId: '1:1045040024438:web:1f0317f5a0a3b685bc4857',
    messagingSenderId: '1045040024438',
    projectId: 'honbab-battle',
    authDomain: 'honbab-battle.firebaseapp.com',
    storageBucket: 'honbab-battle.firebasestorage.app',
  );
}
